[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
specs = "0.20.0"
specs-derive = "0.4.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
