[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
ratatui = "0.29.0"
serde = "1.0.219"
specs = "0.20.0"
specs-derive = "0.4.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
